### PR TITLE
Add initial bmi

### PR DESCRIPTION
**Pull request by mcflugen**
@irbreeves, @anardek This pull request begins the wrapping of *Barrier3d* with a BMI. Thus far, the biggest change is that I've moved your scripts into an installable package, *barrier3d*, and created a new class, *Barrier3d*, that is the model.

Some additional notes:
* *configuration.py*: defines input parameters that can be read either from a *yaml* file, or imported from a *py* file.
* *load_input*: readers for input files, which include the parameter file as well as data files for elevations, storms, etc.
* I've added a seeded random number generator so that we can reproduce runs for testing
* Add a command line interface for using barrier3d
  * `b3d show`: print input files
  * `b3d setup`: create sample input files for a simulation
  * `b3d run`: run a simulation

Still todo:
* [ ] Documentation!
* [ ] Add the BMI
* [ ] Ensure output of this new version matches the old version

### CODE REVIEW

**Comment by anardek** [comment]
Ok, just so I understand this: after you merge the commits to the master you will create a fork on the master in CECL?

**Comment by mcflugen** [comment]
@anardek My intention was to merge this pull request into *master* on *UNC-CECL/Barrier3D*. However, it appears I'm unable to do so (which is why I've sent this pull request to *master* on my fork). I think it might be because forking has been disabled for *UNC-CECL/Barrier3D*. Perhaps forking was disabled after I had created my fork of *Barrier3D*?

**Comment by anardek** [comment]
@mcflugen Ok, I just enabled forking on UNC-CECL and checked that it now works on Barrier3D.

**Comment by mcflugen** [comment]
Duplicate of UNC-CECL/Barrier3D#3. Closing.

**Pull request closed without merging**
